name:                abbrev
version:             0.1.0.0
description:         My attempts at the HackerRank abbreviation problem
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              https://github.com/Nick-Chapman/abbrev.git

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- array
- base >= 4.7 && < 5
- containers
- extra
- split

ghc-options:
- -Wall
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  abbrev-exe:
    main:                Main.hs
    source-dirs:         app
